INSERT INTO disco (nombre, id_autor, anyo) VALUES ('Tentación', 1, '1990');
INSERT INTO disco (nombre, id_autor, anyo) VALUES ('Still got the blues', 2, '1990');
INSERT INTO disco (nombre, id_autor, anyo) VALUES ('After hours', 2, '1992');
INSERT INTO disco (nombre, id_autor, anyo) VALUES ('Los chulos son pa'' cuidarlos', 3, '1900');
INSERT INTO cancion (nombre, id_disco, numero) VALUES ('Tentación', 1, 1);
INSERT INTO cancion (nombre, id_disco, numero) VALUES ('Fueron los celos', 1, 2);
INSERT INTO cancion (nombre, id_disco, numero) VALUES ('Ella es un volcán', 1, 3);
INSERT INTO cancion (nombre, id_disco, numero) VALUES ('Si tú quisieras', 1, 4);
INSERT INTO cancion (nombre, id_disco, numero) VALUES ('Dámelo ya', 1, 5);
INSERT INTO cancion (nombre, id_disco, numero) VALUES ('Llámame', 1, 6);
INSERT INTO cancion (nombre, id_disco, numero) VALUES ('Revolución', 1, 7);
INSERT INTO cancion (nombre, id_disco, numero) VALUES ('Más dura será la caída', 1, 8);
INSERT INTO cancion (nombre, id_disco, numero) VALUES ('Nana', 1, 9);
INSERT INTO cancion (nombre, id_disco, numero) VALUES ('Santa María', 1, 10);
INSERT INTO cancion (nombre, id_disco, numero) VALUES ('Berlín', 1, 11);
INSERT INTO cancion (nombre, id_disco, numero) VALUES ('Moving on', 2, 1);
INSERT INTO cancion (nombre, id_disco, numero) VALUES ('Oh pretty woman', 2, 2);
INSERT INTO cancion (nombre, id_disco, numero) VALUES ('Walking by myself', 2, 3);
INSERT INTO cancion (nombre, id_disco, numero) VALUES ('Still got the blues', 2, 4);
INSERT INTO cancion (nombre, id_disco, numero) VALUES ('Texas strut', 2, 5);
INSERT INTO cancion (nombre, id_disco, numero) VALUES ('Too tired', 2, 6);
INSERT INTO cancion (nombre, id_disco, numero) VALUES ('King of the blues', 2, 7);
INSERT INTO cancion (nombre, id_disco, numero) VALUES ('As the years go passing by', 2, 8);
INSERT INTO cancion (nombre, id_disco, numero) VALUES ('Midnight blues', 2, 9);
INSERT INTO cancion (nombre, id_disco, numero) VALUES ('That kind of woman', 2, 10);
INSERT INTO cancion (nombre, id_disco, numero) VALUES ('All your love', 2, 11);
INSERT INTO cancion (nombre, id_disco, numero) VALUES ('Stop messin’ around', 2, 12);
INSERT INTO cancion (nombre, id_disco, numero) VALUES ('Bonustrack', 2, 13);
INSERT INTO cancion (nombre, id_disco, numero) VALUES ('Cold Day in Hell', 3, 1);
INSERT INTO cancion (nombre, id_disco, numero) VALUES ('Don''t You Lie to Me (I Get Evil)', 3, 2);
INSERT INTO cancion (nombre, id_disco, numero) VALUES ('Story of the Blues', 3, 3);
INSERT INTO cancion (nombre, id_disco, numero) VALUES ('Since I Met You Baby', 3, 4);
INSERT INTO cancion (nombre, id_disco, numero) VALUES ('Separate Ways', 3, 5);
INSERT INTO cancion (nombre, id_disco, numero) VALUES ('Only Fool in Town', 3, 6);
INSERT INTO cancion (nombre, id_disco, numero) VALUES ('Key to Love', 3, 7);
INSERT INTO cancion (nombre, id_disco, numero) VALUES ('Jumpin'' at Shadows', 3, 8);
INSERT INTO cancion (nombre, id_disco, numero) VALUES ('The Blues Is Alright', 3, 9);
INSERT INTO cancion (nombre, id_disco, numero) VALUES ('The Hurt Inside', 3, 10);
INSERT INTO cancion (nombre, id_disco, numero) VALUES ('Nothing''s the Same', 3, 11);
INSERT INTO cancion (nombre, id_disco, numero) VALUES ('Los chulos son pa'' cuidarlos', 4, 1);
INSERT INTO cancion (nombre, id_disco, numero) VALUES ('Tomasa', 4, 2);
INSERT INTO cancion (nombre, id_disco, numero) VALUES ('El apartamento', 4, 3);
INSERT INTO cancion (nombre, id_disco, numero) VALUES ('Se busca un lío', 4, 4);
INSERT INTO cancion (nombre, id_disco, numero) VALUES ('Doña Marina', 4, 5);
INSERT INTO cancion (nombre, id_disco, numero) VALUES ('Tom Sawyer', 4, 6);
INSERT INTO cancion (nombre, id_disco, numero) VALUES ('Señor papá', 4, 7);
INSERT INTO cancion (nombre, id_disco, numero) VALUES ('Cuando navegamos', 4, 8);
INSERT INTO cancion (nombre, id_disco, numero) VALUES ('Micaela', 4, 9);
INSERT INTO cancion (nombre, id_disco, numero) VALUES ('Ajaulilí', 4, 10);
