INSERT INTO produccion (id_persona, id_disco) VALUES (2, 1);
INSERT INTO produccion (id_persona, id_disco) VALUES (30, 2);
INSERT INTO produccion (id_persona, id_disco) VALUES (20, 2);
INSERT INTO produccion (id_persona, id_disco) VALUES (30, 3);
INSERT INTO produccion (id_persona, id_disco) VALUES (20, 3);
INSERT INTO produccion (id_persona, id_disco) VALUES (1, 4);
INSERT INTO colaboracion (id_persona, id_disco, id_cancion, rol) VALUES (3, 1, 9, 'Arreglos');
INSERT INTO colaboracion (id_persona, id_disco, id_cancion, rol) VALUES (3, 1, 2, 'Arreglos');
INSERT INTO colaboracion (id_persona, id_disco, id_cancion, rol) VALUES (3, 1, 4, 'Arreglos');
INSERT INTO colaboracion (id_persona, id_disco, id_cancion, rol) VALUES (3, 1, 11, 'Arreglos');
INSERT INTO colaboracion (id_persona, id_disco, id_cancion, rol) VALUES (21, 1, 2, 'Compuestas, arregladas y preproducidas');
INSERT INTO colaboracion (id_persona, id_disco, id_cancion, rol) VALUES (21, 1, 4, 'Compuestas, arregladas y preproducidas');
INSERT INTO colaboracion (id_persona, id_disco, id_cancion, rol) VALUES (21, 1, 11, 'Compuestas, arregladas y preproducidas');
INSERT INTO colaboracion (id_persona, id_disco, id_cancion, rol) VALUES (22, 1, 2, 'Compuestas, arregladas y preproducidas');
INSERT INTO colaboracion (id_persona, id_disco, id_cancion, rol) VALUES (22, 1, 4, 'Compuestas, arregladas y preproducidas');
INSERT INTO colaboracion (id_persona, id_disco, id_cancion, rol) VALUES (22, 1, 11, 'Compuestas, arregladas y preproducidas');
INSERT INTO colaboracion (id_persona, id_disco, id_cancion, rol) VALUES (23, 1, 2, 'Compuestas, arregladas y preproducidas');
INSERT INTO colaboracion (id_persona, id_disco, id_cancion, rol) VALUES (23, 1, 4, 'Compuestas, arregladas y preproducidas');
INSERT INTO colaboracion (id_persona, id_disco, id_cancion, rol) VALUES (23, 1, 11, 'Compuestas, arregladas y preproducidas');
INSERT INTO colaboracion (id_persona, id_disco, rol) VALUES (3, 1, 'Piano y teclados');
INSERT INTO colaboracion (id_persona, id_disco, rol) VALUES (4, 1, 'Arreglos de cuerda');
INSERT INTO colaboracion (id_persona, id_disco, rol) VALUES (5, 1, 'Instrumentos');
INSERT INTO colaboracion (id_persona, id_disco, rol) VALUES (6, 1, 'Violín');
INSERT INTO colaboracion (id_persona, id_disco, rol) VALUES (7, 1, 'Violín');
INSERT INTO colaboracion (id_persona, id_disco, rol) VALUES (8, 1, 'Viola');
INSERT INTO colaboracion (id_persona, id_disco, rol) VALUES (9, 1, 'Violonchelo');
INSERT INTO colaboracion (id_persona, id_disco, rol) VALUES (10, 1, 'Viento-metal');
INSERT INTO colaboracion (id_persona, id_disco, rol) VALUES (11, 1, 'Trompeta');
INSERT INTO colaboracion (id_persona, id_disco, rol) VALUES (12, 1, 'Trombón');
INSERT INTO colaboracion (id_persona, id_disco, rol) VALUES (13, 1, 'Saxo tenor');
INSERT INTO colaboracion (id_persona, id_disco, rol) VALUES (14, 1, 'Coros');
INSERT INTO colaboracion (id_persona, id_disco, rol) VALUES (15, 1, 'Coros');
INSERT INTO colaboracion (id_persona, id_disco, rol) VALUES (16, 1, 'Batería');
INSERT INTO colaboracion (id_persona, id_disco, rol) VALUES (17, 1, 'Ingeniero sonido y mezclas');
INSERT INTO colaboracion (id_persona, id_disco, rol) VALUES (18, 1, 'Ingeniero sonido');
INSERT INTO colaboracion (id_persona, id_disco, rol) VALUES (19, 1, 'Asistente ingeniero');
INSERT INTO colaboracion (id_persona, id_disco, rol) VALUES (20, 2, 'Engineered and mixed');
INSERT INTO colaboracion (id_persona, id_disco, rol) VALUES (24, 2, 'Assistance');
INSERT INTO colaboracion (id_persona, id_disco, rol) VALUES (25, 2, 'Assistance');
INSERT INTO colaboracion (id_persona, id_disco, rol) VALUES (26, 2, 'Assistance');
INSERT INTO colaboracion (id_persona, id_disco, rol) VALUES (27, 2, 'Assistance');
INSERT INTO colaboracion (id_persona, id_disco, rol) VALUES (28, 2, 'Assistance');
INSERT INTO colaboracion (id_persona, id_disco, rol) VALUES (29, 2, 'Assistance');
INSERT INTO colaboracion (id_persona, id_disco, rol) VALUES (77, 2, 'Strings conducted');
INSERT INTO colaboracion (id_persona, id_disco, rol) VALUES (30, 2, 'All horns arranged');
INSERT INTO colaboracion (id_persona, id_disco, rol) VALUES (77, 2, 'All horns arranged');
INSERT INTO colaboracion (id_persona, id_disco, id_cancion, rol) VALUES (30, 2, 15, 'String arranged');
INSERT INTO colaboracion (id_persona, id_disco, id_cancion, rol) VALUES (77, 2, 15, 'String arranged');
INSERT INTO colaboracion (id_persona, id_disco, id_cancion, rol) VALUES (30, 2, 20, 'String arranged');
INSERT INTO colaboracion (id_persona, id_disco, id_cancion, rol) VALUES (77, 2, 20, 'String arranged');
INSERT INTO colaboracion (id_persona, id_disco, id_cancion, rol) VALUES (30, 2, 12, 'Written');
INSERT INTO colaboracion (id_persona, id_disco, id_cancion, rol) VALUES (31, 2, 13, 'Written');
INSERT INTO colaboracion (id_persona, id_disco, id_cancion, rol) VALUES (32, 2, 14, 'Written');
INSERT INTO colaboracion (id_persona, id_disco, id_cancion, rol) VALUES (30, 2, 15, 'Written');
INSERT INTO colaboracion (id_persona, id_disco, id_cancion, rol) VALUES (30, 2, 16, 'Written');
INSERT INTO colaboracion (id_persona, id_disco, id_cancion, rol) VALUES (33, 2, 17, 'Written');
INSERT INTO colaboracion (id_persona, id_disco, id_cancion, rol) VALUES (34, 2, 17, 'Written');
INSERT INTO colaboracion (id_persona, id_disco, id_cancion, rol) VALUES (35, 2, 17, 'Written');
INSERT INTO colaboracion (id_persona, id_disco, id_cancion, rol) VALUES (30, 2, 18, 'Written');
INSERT INTO colaboracion (id_persona, id_disco, id_cancion, rol) VALUES (36, 2, 19, 'Written');
INSERT INTO colaboracion (id_persona, id_disco, id_cancion, rol) VALUES (30, 2, 20, 'Written');
INSERT INTO colaboracion (id_persona, id_disco, id_cancion, rol) VALUES (37, 2, 21, 'Written');
INSERT INTO colaboracion (id_persona, id_disco, id_cancion, rol) VALUES (38, 2, 22, 'Written');
INSERT INTO colaboracion (id_persona, id_disco, id_cancion, rol) VALUES (39, 2, 23, 'Written');
INSERT INTO colaboracion (id_persona, id_disco, id_cancion, rol) VALUES (30, 2, 24, 'Written');
INSERT INTO colaboracion (id_persona, id_disco, id_cancion, rol) VALUES (30, 2, 12, 'Guitar/Vocals');
INSERT INTO colaboracion (id_persona, id_disco, id_cancion, rol) VALUES (40, 2, 12, 'Piano');
INSERT INTO colaboracion (id_persona, id_disco, id_cancion, rol) VALUES (41, 2, 12, 'Bass');
INSERT INTO colaboracion (id_persona, id_disco, id_cancion, rol) VALUES (42, 2, 12, 'Drums');
INSERT INTO colaboracion (id_persona, id_disco, id_cancion, rol) VALUES (30, 2, 13, 'Guitar/Vocals');
INSERT INTO colaboracion (id_persona, id_disco, id_cancion, rol) VALUES (77, 2, 13, 'Guitar');
INSERT INTO colaboracion (id_persona, id_disco, id_cancion, rol) VALUES (77, 2, 13, 'Hammond Organ');
INSERT INTO colaboracion (id_persona, id_disco, id_cancion, rol) VALUES (41, 2, 13, 'Bass');
INSERT INTO colaboracion (id_persona, id_disco, id_cancion, rol) VALUES (42, 2, 13, 'Drums');
INSERT INTO colaboracion (id_persona, id_disco, id_cancion, rol) VALUES (43, 2, 13, 'Trumpet');
INSERT INTO colaboracion (id_persona, id_disco, id_cancion, rol) VALUES (44, 2, 13, 'Alto/Tenor Saxes');
INSERT INTO colaboracion (id_persona, id_disco, id_cancion, rol) VALUES (45, 2, 13, 'Tenor Sax');
INSERT INTO colaboracion (id_persona, id_disco, id_cancion, rol) VALUES (46, 2, 13, 'Baritone Sax');
INSERT INTO colaboracion (id_persona, id_disco, id_cancion, rol) VALUES (30, 2, 14, 'Guitar/Vocals');
INSERT INTO colaboracion (id_persona, id_disco, id_cancion, rol) VALUES (40, 2, 14, 'Piano');
INSERT INTO colaboracion (id_persona, id_disco, id_cancion, rol) VALUES (41, 2, 14, 'Bass');
INSERT INTO colaboracion (id_persona, id_disco, id_cancion, rol) VALUES (42, 2, 14, 'Drums');
INSERT INTO colaboracion (id_persona, id_disco, id_cancion, rol) VALUES (44, 2, 14, 'Harmonica');
INSERT INTO colaboracion (id_persona, id_disco, id_cancion, rol) VALUES (30, 2, 15, 'Guitar/Vocals');
INSERT INTO colaboracion (id_persona, id_disco, id_cancion, rol) VALUES (77, 2, 15, 'Keyboards');
INSERT INTO colaboracion (id_persona, id_disco, id_cancion, rol) VALUES (47, 2, 15, 'Piano');
INSERT INTO colaboracion (id_persona, id_disco, id_cancion, rol) VALUES (41, 2, 15, 'Bass');
INSERT INTO colaboracion (id_persona, id_disco, id_cancion, rol) VALUES (42, 2, 15, 'Drums');
INSERT INTO colaboracion (id_persona, id_disco, id_cancion, rol) VALUES (48, 2, 15, 'String section led');
INSERT INTO colaboracion (id_persona, id_disco, id_cancion, rol) VALUES (30, 2, 16, 'Guitar/Vocals');
INSERT INTO colaboracion (id_persona, id_disco, id_cancion, rol) VALUES (77, 2, 16, 'Keyboards');
INSERT INTO colaboracion (id_persona, id_disco, id_cancion, rol) VALUES (49, 2, 16, 'Bass');
INSERT INTO colaboracion (id_persona, id_disco, id_cancion, rol) VALUES (50, 2, 16, 'Drums');
INSERT INTO colaboracion (id_persona, id_disco, id_cancion, rol) VALUES (30, 2, 17, 'Guitar/Vocals');
INSERT INTO colaboracion (id_persona, id_disco, id_cancion, rol) VALUES (51, 2, 17, 'Guitar');
INSERT INTO colaboracion (id_persona, id_disco, id_cancion, rol) VALUES (77, 2, 17, 'Piano');
INSERT INTO colaboracion (id_persona, id_disco, id_cancion, rol) VALUES (41, 2, 17, 'Bass');
INSERT INTO colaboracion (id_persona, id_disco, id_cancion, rol) VALUES (42, 2, 17, 'Drums');
INSERT INTO colaboracion (id_persona, id_disco, id_cancion, rol) VALUES (52, 2, 17, 'Trumpet');
INSERT INTO colaboracion (id_persona, id_disco, id_cancion, rol) VALUES (44, 2, 17, 'Alto Sax');
INSERT INTO colaboracion (id_persona, id_disco, id_cancion, rol) VALUES (53, 2, 17, 'Tenor Sax');
INSERT INTO colaboracion (id_persona, id_disco, id_cancion, rol) VALUES (46, 2, 17, 'Baritone Sax');
INSERT INTO colaboracion (id_persona, id_disco, id_cancion, rol) VALUES (30, 2, 18, 'Guitar/Vocals');
INSERT INTO colaboracion (id_persona, id_disco, id_cancion, rol) VALUES (77, 2, 18, 'Hammond Organ');
INSERT INTO colaboracion (id_persona, id_disco, id_cancion, rol) VALUES (41, 2, 18, 'Bass');
INSERT INTO colaboracion (id_persona, id_disco, id_cancion, rol) VALUES (50, 2, 18, 'Drums');
INSERT INTO colaboracion (id_persona, id_disco, id_cancion, rol) VALUES (43, 2, 18, 'Trumpet');
INSERT INTO colaboracion (id_persona, id_disco, id_cancion, rol) VALUES (44, 2, 18, 'Alto/Tenor Saxes');
INSERT INTO colaboracion (id_persona, id_disco, id_cancion, rol) VALUES (45, 2, 18, 'Tenor Sax');
INSERT INTO colaboracion (id_persona, id_disco, id_cancion, rol) VALUES (46, 2, 18, 'Baritone Sax');
INSERT INTO colaboracion (id_persona, id_disco, id_cancion, rol) VALUES (30, 2, 19, 'Guitar/Vocals');
INSERT INTO colaboracion (id_persona, id_disco, id_cancion, rol) VALUES (77, 2, 19, 'Hammond Organ');
INSERT INTO colaboracion (id_persona, id_disco, id_cancion, rol) VALUES (47, 2, 19, 'Piano');
INSERT INTO colaboracion (id_persona, id_disco, id_cancion, rol) VALUES (49, 2, 19, 'Bass');
INSERT INTO colaboracion (id_persona, id_disco, id_cancion, rol) VALUES (50, 2, 19, 'Drums');
INSERT INTO colaboracion (id_persona, id_disco, id_cancion, rol) VALUES (44, 2, 19, 'Alto Sax');
INSERT INTO colaboracion (id_persona, id_disco, id_cancion, rol) VALUES (46, 2, 19, 'Baritone Sax');
INSERT INTO colaboracion (id_persona, id_disco, id_cancion, rol) VALUES (30, 2, 20, 'Guitar/Vocals');
INSERT INTO colaboracion (id_persona, id_disco, id_cancion, rol) VALUES (40, 2, 20, 'Electric Piano');
INSERT INTO colaboracion (id_persona, id_disco, id_cancion, rol) VALUES (41, 2, 20, 'Bass');
INSERT INTO colaboracion (id_persona, id_disco, id_cancion, rol) VALUES (42, 2, 20, 'Drums');
INSERT INTO colaboracion (id_persona, id_disco, id_cancion, rol) VALUES (48, 2, 20, 'String section led');
INSERT INTO colaboracion (id_persona, id_disco, id_cancion, rol) VALUES (30, 2, 21, 'Guitar/Vocals');
INSERT INTO colaboracion (id_persona, id_disco, id_cancion, rol) VALUES (37, 2, 21, 'Slide and Rhythm Guitar/Backing Vocals');
INSERT INTO colaboracion (id_persona, id_disco, id_cancion, rol) VALUES (47, 2, 21, 'Piano');
INSERT INTO colaboracion (id_persona, id_disco, id_cancion, rol) VALUES (49, 2, 21, 'Bass');
INSERT INTO colaboracion (id_persona, id_disco, id_cancion, rol) VALUES (42, 2, 21, 'Drums');
INSERT INTO colaboracion (id_persona, id_disco, id_cancion, rol) VALUES (54, 2, 21, 'Trumpet');
INSERT INTO colaboracion (id_persona, id_disco, id_cancion, rol) VALUES (44, 2, 21, 'Alto Sax');
INSERT INTO colaboracion (id_persona, id_disco, id_cancion, rol) VALUES (45, 2, 21, 'Tenor Sax');
INSERT INTO colaboracion (id_persona, id_disco, id_cancion, rol) VALUES (46, 2, 21, 'Baritone Sax');
INSERT INTO colaboracion (id_persona, id_disco, id_cancion, rol) VALUES (30, 2, 22, 'Guitar/Vocals');
INSERT INTO colaboracion (id_persona, id_disco, id_cancion, rol) VALUES (40, 2, 22, 'Hammond Organ');
INSERT INTO colaboracion (id_persona, id_disco, id_cancion, rol) VALUES (41, 2, 22, 'Bass');
INSERT INTO colaboracion (id_persona, id_disco, id_cancion, rol) VALUES (42, 2, 22, 'Drums');
INSERT INTO colaboracion (id_persona, id_disco, id_cancion, rol) VALUES (30, 2, 23, 'Guitar/Vocals');
INSERT INTO colaboracion (id_persona, id_disco, id_cancion, rol) VALUES (40, 2, 23, 'Piano');
INSERT INTO colaboracion (id_persona, id_disco, id_cancion, rol) VALUES (41, 2, 23, 'Bass');
INSERT INTO colaboracion (id_persona, id_disco, id_cancion, rol) VALUES (42, 2, 23, 'Drums');
INSERT INTO colaboracion (id_persona, id_disco, id_cancion, rol) VALUES (44, 2, 23, 'Saxes');
INSERT INTO colaboracion (id_persona, id_disco, id_cancion, rol) VALUES (30, 2, 24, 'Guitar/Vocals');
INSERT INTO colaboracion (id_persona, id_disco, id_cancion, rol) VALUES (41, 2, 24, 'Bass');
INSERT INTO colaboracion (id_persona, id_disco, id_cancion, rol) VALUES (42, 2, 24, 'Drums');
INSERT INTO colaboracion (id_persona, id_disco, rol) VALUES (20, 3, 'Engineered');
INSERT INTO colaboracion (id_persona, id_disco, rol) VALUES (56, 3, 'Engineered');
INSERT INTO colaboracion (id_persona, id_disco, rol) VALUES (29, 3, 'Engineered');
INSERT INTO colaboracion (id_persona, id_disco, rol) VALUES (57, 3, 'Assisted');
INSERT INTO colaboracion (id_persona, id_disco, rol) VALUES (24, 3, 'Assisted');
INSERT INTO colaboracion (id_persona, id_disco, rol) VALUES (58, 3, 'Assisted');
INSERT INTO colaboracion (id_persona, id_disco, rol) VALUES (59, 3, 'Assisted');
INSERT INTO colaboracion (id_persona, id_disco, rol) VALUES (60, 3, 'Assisted');
INSERT INTO colaboracion (id_persona, id_disco, rol) VALUES (61, 3, 'Assisted');
INSERT INTO colaboracion (id_persona, id_disco, rol) VALUES (62, 3, 'Assisted');
INSERT INTO colaboracion (id_persona, id_disco, rol) VALUES (30, 3, 'Brass & string arrangements');
INSERT INTO colaboracion (id_persona, id_disco, rol) VALUES (63, 3, 'Brass & string arrangements');
INSERT INTO colaboracion (id_persona, id_disco, rol) VALUES (48, 3, 'String section led');
INSERT INTO colaboracion (id_persona, id_disco, rol) VALUES (63, 3, 'Keyboards');
INSERT INTO colaboracion (id_persona, id_disco, rol) VALUES (69, 3, 'Bass');
INSERT INTO colaboracion (id_persona, id_disco, rol) VALUES (49, 3, 'Bass');
INSERT INTO colaboracion (id_persona, id_disco, rol) VALUES (70, 3, 'Bass');
INSERT INTO colaboracion (id_persona, id_disco, rol) VALUES (42, 3, 'Drums');
INSERT INTO colaboracion (id_persona, id_disco, rol) VALUES (71, 3, 'Drums');
INSERT INTO colaboracion (id_persona, id_disco, rol) VALUES (54, 3, 'Horns');
INSERT INTO colaboracion (id_persona, id_disco, rol) VALUES (44, 3, 'Horns');
INSERT INTO colaboracion (id_persona, id_disco, rol) VALUES (45, 3, 'Horns');
INSERT INTO colaboracion (id_persona, id_disco, rol) VALUES (46, 3, 'Horns');
INSERT INTO colaboracion (id_persona, id_disco, rol) VALUES (72, 3, 'The Memphis Horns');
INSERT INTO colaboracion (id_persona, id_disco, rol) VALUES (73, 3, 'The Memphis Horns');
INSERT INTO colaboracion (id_persona, id_disco, rol) VALUES (74, 3, 'Backing vocals');
INSERT INTO colaboracion (id_persona, id_disco, rol) VALUES (75, 3, 'Backing vocals');
INSERT INTO colaboracion (id_persona, id_disco, rol) VALUES (76, 3, 'Oboe');
INSERT INTO colaboracion (id_persona, id_disco, id_cancion, rol) VALUES (20, 3, 25, 'Mixed');
INSERT INTO colaboracion (id_persona, id_disco, id_cancion, rol) VALUES (20, 3, 26, 'Mixed');
INSERT INTO colaboracion (id_persona, id_disco, id_cancion, rol) VALUES (55, 3, 27, 'Mixed');
INSERT INTO colaboracion (id_persona, id_disco, id_cancion, rol) VALUES (20, 3, 28, 'Mixed');
INSERT INTO colaboracion (id_persona, id_disco, id_cancion, rol) VALUES (20, 3, 29, 'Mixed');
INSERT INTO colaboracion (id_persona, id_disco, id_cancion, rol) VALUES (20, 3, 30, 'Mixed');
INSERT INTO colaboracion (id_persona, id_disco, id_cancion, rol) VALUES (20, 3, 31, 'Mixed');
INSERT INTO colaboracion (id_persona, id_disco, id_cancion, rol) VALUES (20, 3, 32, 'Mixed');
INSERT INTO colaboracion (id_persona, id_disco, id_cancion, rol) VALUES (20, 3, 33, 'Mixed');
INSERT INTO colaboracion (id_persona, id_disco, id_cancion, rol) VALUES (20, 3, 34, 'Mixed');
INSERT INTO colaboracion (id_persona, id_disco, id_cancion, rol) VALUES (20, 3, 35, 'Mixed');
INSERT INTO colaboracion (id_persona, id_disco, id_cancion, rol) VALUES (30, 3, 25, 'Written');
INSERT INTO colaboracion (id_persona, id_disco, id_cancion, rol) VALUES (65, 3, 26, 'Written');
INSERT INTO colaboracion (id_persona, id_disco, id_cancion, rol) VALUES (30, 3, 27, 'Written');
INSERT INTO colaboracion (id_persona, id_disco, id_cancion, rol) VALUES (30, 3, 28, 'Written');
INSERT INTO colaboracion (id_persona, id_disco, id_cancion, rol) VALUES (30, 3, 29, 'Written');
INSERT INTO colaboracion (id_persona, id_disco, id_cancion, rol) VALUES (30, 3, 30, 'Written');
INSERT INTO colaboracion (id_persona, id_disco, id_cancion, rol) VALUES (66, 3, 31, 'Written');
INSERT INTO colaboracion (id_persona, id_disco, id_cancion, rol) VALUES (67, 3, 32, 'Written');
INSERT INTO colaboracion (id_persona, id_disco, id_cancion, rol) VALUES (68, 3, 33, 'Written');
INSERT INTO colaboracion (id_persona, id_disco, id_cancion, rol) VALUES (30, 3, 34, 'Written');
INSERT INTO colaboracion (id_persona, id_disco, id_cancion, rol) VALUES (30, 3, 35, 'Written');
INSERT INTO colaboracion (id_persona, id_disco, id_cancion, rol) VALUES (64, 3, 28, 'Special guests');
INSERT INTO colaboracion (id_persona, id_disco, id_cancion, rol) VALUES (51, 3, 33, 'Special guests');
